/**
 * This file automatically generated by Build System - DO NOT EDIT
 */

#ifndef _COPYRIGHT_9412_h
#define _COPYRIGHT_9412_h

#define COPYRIGHT_s "SaSString-debug is Copyright (C) 2000-2019 Douglas Mark Royer, All Rights Reserved"

#ifdef TARG_BINARY_s
#undef TARG_BINARY_s
#endif // TARG_BINARY_s
#define TARG_BINARY_s "SaSString-debug"

#ifdef PSTAMP_s
#undef PSTAMP_s
#endif // PSTAMP_s
#define PSTAMP_s "2019.10.28.11.52.18"

#ifdef OS_s
#undef OS_s
#endif // OS_s
#define OS_s "Linux_RH"

#ifdef OSVER_s
#undef OSVER_s
#endif // OSVER_s
#define OSVER_s "x86_64"

#ifdef VERSION_s
#undef VERSION_s
#endif // VERSION_s
#define VERSION_s "SaSString-debug:SaS:REV=2015.1.0.0:2019.10.28.11.52.18"

#ifdef FULLVERSION_s
#undef FULLVERSION_s
#endif // FULLVERSION_s
#define FULLVERSION_s "2015.1.0.0"

#ifdef PROTOSUBDIR_s
#undef PROTOSUBDIR_s
#endif // PROTOSUBDIR_s
#define PROTOSUBDIR_s "Linux.x86_64.PC"

#ifdef SASINC_s
#undef SASINC_s
#endif // SASINC_s
#define SASINC_s "http://SoftwareAndServices.US/SaSString"

#ifdef CONFIGDIR_s
#undef CONFIGDIR_s
#endif // CONFIGDIR_s
#define CONFIGDIR_s "/opt/SaS/etc"

#ifdef PROTO_s
#undef PROTO_s
#endif // PROTO_s
#define PROTO_s "/Proto"

#ifdef INSTALLDIR_s
#undef INSTALLDIR_s
#endif // INSTALLDIR_s
#define INSTALLDIR_s "/opt/SaS"

#ifdef TARG_CAT_s
#undef TARG_CAT_s
#endif // TARG_CAT_s
#define TARG_CAT_s "SaSString"

#ifdef DEBUG_i
#undef DEBUG_i
#endif // DEBUG_i 1
#define DEBUG_i 1

extern const char * const	SaSString_CopyRightNotice_s;
extern const char * const	SaSString_PStamp_s;
extern const char * const	SaSString_Os_s;
extern const char * const	SaSString_OsVer_s;
extern const char * const	SaSString_Version_s;
extern const char * const	SaSString_FullVersion_s;
extern const char * const	SaSString_TargBinary_s;
extern const char * const	SaSString_Proto_s;
extern const char * const	SaSString_ProtoSubDir_s;
extern const char * const	SaSString_SaSInc_s;
extern const char * const	SaSString_ConfigDir_s;
extern const char * const	SaSString_Proto_s;
extern const char * const	SaSString_InstallDir_s;
extern const char * const	SaSString_TargCat_s;
extern const int		SaSString_Debug_i;

#endif //_COPYRIGHT_9412_h

